name: Supabase Check

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 22 */3 * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase REST endpoint
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          set -e

          curl -fsS -i "https://tmoqqolmpxoeliyknbaz.supabase.co/rest/v1/players?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}"
